blueprint:
  name: Energy Optimizer - Daily Battery Optimization
  description: Generate and apply optimal daily battery schedule
  domain: automation
  input:
    schedule_time:
      name: Schedule Time
      description: Time to generate next day's schedule
      default: "22:00:00"
      selector:
        time:
    optimization_goal:
      name: Optimization Goal
      description: Strategy for battery optimization
      default: "balanced"
      selector:
        select:
          options:
            - label: "Cost Minimize"
              value: "cost_minimize"
            - label: "Self Consumption"
              value: "self_consumption"
            - label: "Balanced"
              value: "balanced"
    notification_entity:
      name: Notification Entity (Optional)
      description: Entity to send notifications to
      default: []
      selector:
        entity:
          domain: notify

trigger:
  - platform: time
    at: !input schedule_time

action:
  - service: energy_optimizer.optimize_battery_schedule
    data:
      optimization_goal: !input optimization_goal
    response_variable: schedule_result
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notification_entity | length > 0 }}"
        sequence:
          - service: notify.{{ notification_entity }}
            data:
              title: "Energy Optimizer - Daily Schedule"
              message: >
                Tomorrow's optimization schedule generated:
                Estimated daily cost: {{ schedule_result.estimated_daily_cost_pln | default('N/A') }} PLN
                Estimated savings: {{ schedule_result.estimated_daily_savings_pln | default('N/A') }} PLN

mode: single
