blueprint:
  name: Energy Optimizer - Smart Grid Selling
  description: Automatically sell surplus energy during expensive periods
  domain: automation
  input:
    expensive_window_sensor:
      name: Expensive Window Sensor
      description: Binary sensor indicating expensive price window
      selector:
        entity:
          domain: binary_sensor
    surplus_energy_sensor:
      name: Surplus Energy Sensor
      description: Sensor showing available surplus energy
      selector:
        entity:
          domain: sensor
          device_class: energy
    min_surplus_threshold:
      name: Minimum Surplus Threshold
      description: Minimum surplus energy required to sell (kWh)
      default: 5
      selector:
        number:
          min: 0
          max: 20
          step: 0.5
          unit_of_measurement: "kWh"
    min_profit_margin:
      name: Minimum Profit Margin
      description: Minimum price premium required to sell (%)
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    auto_work_mode:
      name: Auto Switch Work Mode
      description: Automatically switch inverter to selling mode
      default: true
      selector:
        boolean:
    notification_entity:
      name: Notification Entity (Optional)
      description: Entity to send notifications to
      default: []
      selector:
        entity:
          domain: notify

trigger:
  - platform: state
    entity_id: !input expensive_window_sensor
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input surplus_energy_sensor
    above: !input min_surplus_threshold

action:
  - service: energy_optimizer.calculate_sell_energy
    data:
      min_profit_margin: !input min_profit_margin
      auto_set_work_mode: !input auto_work_mode
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notification_entity | length > 0 }}"
        sequence:
          - service: notify.{{ notification_entity }}
            data:
              title: "Energy Optimizer"
              message: "Started grid selling during expensive window"

mode: single
