blueprint:
  name: Energy Optimizer - Smart Grid Charging
  description: Automatically charge battery during cheap electricity periods
  domain: automation
  input:
    cheapest_window_sensor:
      name: Cheapest Window Sensor
      description: Binary sensor indicating cheapest price window
      selector:
        entity:
          domain: binary_sensor
    battery_soc_sensor:
      name: Battery SOC Sensor
      description: Sensor showing battery state of charge
      selector:
        entity:
          domain: sensor
          device_class: battery
    max_soc_threshold:
      name: Maximum SOC Threshold
      description: Don't charge if battery is above this level
      default: 80
      selector:
        number:
          min: 50
          max: 100
          unit_of_measurement: "%"
    charge_hours:
      name: Charge Coverage Hours
      description: Number of hours to cover with charge
      default: 12
      selector:
        number:
          min: 1
          max: 24
          unit_of_measurement: "hours"
    notification_entity:
      name: Notification Entity (Optional)
      description: Entity to send notifications to
      default: []
      selector:
        entity:
          domain: notify

trigger:
  - platform: state
    entity_id: !input cheapest_window_sensor
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input battery_soc_sensor
    below: !input max_soc_threshold

action:
  - service: energy_optimizer.calculate_charge_soc
    data:
      hours: !input charge_hours
      force_charge: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notification_entity | length > 0 }}"
        sequence:
          - service: notify.{{ notification_entity }}
            data:
              title: "Energy Optimizer"
              message: "Started grid charging during cheap window"

mode: single
